name: ar_quido_example
description: Demonstrates how to use the ar_quido plugin.
publish_to: 'none'

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  ar_quido:
    path: ../
  cupertino_icons: 1.0.5
  flutter:
    sdk: flutter
  permission_handler: 10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_quido: 0.4.0


flutter:
  uses-material-design: true
  assets:
    - assets/reference_images/
